<?php

//use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_theme().
 */
function valida_email_theme($existing, $type, $theme, $path) {
  return [
    'my_template' => [
    'variables' => ['nid' => NULL],
    ]
  ];
}

function valida_email_page_attachments(&$page) {
  $page['#attached']['library'][] = 'valida_email/valida_email';
  
}

function valida_email_preprocess_node(&$node) {


}
