<?php

use Drupal\Core\Access\AccessibleInterface;
use Drupal\Core\Cache\CacheableDependencyInterface;
use Drupal\Core\Entity\ContentEntityBase;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function fflchsic_help($path, $arg) {
  switch ($path) {
    case "help.page.fflchsic":
      return '' . t("TODO: implement Help page") . '';
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert() for node entities.
 *
 * This tests saving a node on node insert.
 *
 */

function fflchsic_entity_prepare_form(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() === 'contact_message' && ( $entity->bundle() === 'assessoria_de_imprensa' || $entity->bundle() === 'fale_conosco' )) {
    $unique = date("Y") . substr(uniqid(),9,4); 
    $entity->set('field_protocolo',$unique);
  }
}
