smtp_on: true
smtp_host: smtp.gmail.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_username: 'noreply.sites.fflch@usp.br'
smtp_password: '__senha_noreply__'
smtp_from: ''
smtp_fromname: ''
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
langcode: pt-br
